spring.application.name=FitCore

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/fitcore?sslMode=VERIFY_IDENTITY
spring.datasource.username=ZMhDMT4EvA6yzLU.root
spring.datasource.password=Xv8tgZe43bnvkLSU

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luxspams@gmail.com
spring.mail.password=flui mihl nkxr wvwa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true