spring.application.name=FitCore

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/fitcore?sslMode=VERIFY_IDENTITY
spring.datasource.username=ZMhDMT4EvA6yzLU.root
spring.datasource.password=Xv8tgZe43bnvkLSU

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true